steps:
  - id: 'Generate manifests'
    name: 'gcr.io/cloud-builders/gcloud@sha256:37412572bf359eb005a097a8514a0fb76e80a221cb27142daa12348bb3bf5f19'
    dir: kubernetes
    script: |
      #!/usr/bin/env bash
      set -euxo pipefail

      # mirror kustomize-controller build options
      kustomize_flags=("--load-restrictor=LoadRestrictionsNone")
      kustomize_config="kustomization.yaml"

      echo "INFO - Generating kustomize overlays"
      find . -type f -name $kustomize_config -print0 | while IFS= read -r -d $'\0' file;
        do
          echo "INFO - Generating kustomization ${file/%$kustomize_config}"
          kustomize build "${file/%$kustomize_config}" "${kustomize_flags[@]}" >> /workspace/resources.yaml
          echo "---" >> /workspace/resources.yaml
      done

  - id: Validate schema
    name: 'ghcr.io/yannh/kubeconform:latest-alpine@sha256:824e0c248809e4b2da2a768b16b107cf17ada88a89ec6aa6050e566ba93ebbc6'
    dir: kubernetes
    args:
      - -skip=Secret
      - -strict
      - -ignore-missing-schemas
      - -schema-location=default
      - >-
        -schema-location=
        'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json'
      - -verbose
      - /workspace/resources.yaml
